#pragma kernel CSMain

struct Triangle
{
    float3 position[3];
};

AppendStructuredBuffer<Triangle> triangles;

RWTexture2D<float4> Result;

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	Triangle polygon;
	polygon.position[0] = float3(id.x, id.x, id.x);
	polygon.position[1] = float3(id.x, id.x + 1, id.x);
    polygon.position[2] = float3(id.x, id.x, id.x + 1);

	triangles.Append(polygon);
}